package nl.tsuriani.rpsls.infra.messaging.event;

public enum EventType {
	PLAYER_JOINED,
	PLAYER_REGISTERED,
	SESSION_IS_COMPLETE,
	NEW_ROUND_STARTED,
	PLAYER_CHOSE,
	SCORE_UPDATED,
	SESSION_IS_TERMINATED,
	SESSION_IS_CANCELLED
}
